### ISSUE TITLE
Feature: Allow Nav logo to be configurable

### ISSUE THREAD

**Issue by jordojordo** [kyverno/policy-reporter-ui#475]
The latest version of the Policy Reporter UI now has a logo within the Navigation bar. It would be nice if this could be configurable/removable when deploying with the UI from the [official Helm chart](https://artifacthub.io/packages/helm/policy-reporter/policy-reporter).

![Image](https://github.com/user-attachments/assets/5cfd8618-e674-48b6-8900-1bf5334c7e0c)

**Comment by fjogeleit** [comment]
The latest helm chart version (v3.0.4) has two new configurations for the UI. You can either disable the logo or provide a path to custom one.

```yaml
ui:
  logo:
    #disabled: true
    path: https://avatars.githubusercontent.com/u/80915497?s=200&v=4
```
